title: My Testing GitHub Page
author: Zheng Fu
email: zf38@cornell.edu
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my GitHub page.

# social links
twitter_username: zhengfu23
github_username:  zhengfu23

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
